### ISSUE TITLE
Accessibility: Add button for subtitles with official "CC" logo

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#19]

**Comment by cgruber-uos** [comment]
We have the subtitle-logo-discussion also with OC Editor, see https://github.com/opencast/opencast-editor/issues/897

I would propose to not use the cc-logo because "closed captioning", what cc means, is an English term and not so universal understandable, e.g. in German speaking television we have the UT logo (DE "Untertitel" = subtitle) as icon. A more universal, not language related logo would be: 

![2023-01-06 16_35_51-React Icons – Mozilla Firefox](https://user-images.githubusercontent.com/101632236/211045058-a0647fde-746c-4257-a5d9-81f97414971a.png)

YouTube is using this also:

![2023-01-06 16_24_13-](https://user-images.githubusercontent.com/101632236/211042852-3f53d6c3-aaed-4e94-9741-5e9937674e68.png)

For OC Editor we have planed to use the Icons form the React iconset: https://react-icons.github.io/react-icons/search?q=subtitles

**Comment by oas777** [comment]
Thanks, Clemens. I'm a bit surprised (at YouTube's decision) and others (Vimeo, http://www.mediaelementjs.com/) use CC. I've raised the issue with colleagues from ZHAW who did the accessibility review.

**Comment by oas777** [comment]
It seems YouTube uses a CC symbol in native English-speaking areas, cf. https://tinyurl.com/2krmqr6m. Given we won't have that much flexibility, we might use what they use for the rest of the world. Oriane is also fine with this.

**Comment by cgruber-uos** [comment]
> It seems YouTube uses a CC symbol in native English-speaking areas, cf. https://tinyurl.com/2krmqr6m.

This is a 4 year old video, so I think it was that time the case but is the no more, have a look e.g. at https://www.youtube.com/watch?v=Ad_TEk94B9Q there is also the new one, also in the YT backend: 

![2023-01-24 15_20_27-Greenshot](https://user-images.githubusercontent.com/101632236/214320487-aa25d98f-0d57-4b92-9fb9-8a3d58803aab.png)

**Comment by oas777** [comment]
Interesting. https://support.google.com/youtube/answer/2734796?hl=en&ref_topic=7296214 is the current explanation on how to add subtitles and it shows a CC symbol... 
![image](https://user-images.githubusercontent.com/1752342/214333607-600bc00f-c24d-42ec-8f43-24ea167e6a98.png)

**Comment by oas777** [comment]
Could you make

![grafik](https://user-images.githubusercontent.com/1752342/233578249-5e077992-7b6d-4743-ac32-ee47a4ccd3d2.png)

look more like the one discussed?

![grafik](https://user-images.githubusercontent.com/1752342/233578362-e357e4bd-f464-4671-ac9b-a2c188373cf0.png)

? This one reminds me of slides and their content...

**Comment by miesgre** [comment]
Done!

**Comment by oas777** [comment]
Thanks.
