### ISSUE TITLE
New test video has different contral bar symbols

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#28]
Miguel, https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls has no "view" button and there is a "Select video quality" option under "Settings" (which doesn't really work because it always switches back to "auto"). How and why is this different from https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote?

**Comment by miesgre** [comment]
> Miguel, https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls has no "view" button 

The button was hidden because this demo didn't have the frame list. I added it and now the button is visible.

> and there is a "Select video quality" option under "Settings" (which doesn't really work because it always switches back to "auto"). How and why is this different from https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote?

The old video (`belmar-multiresolution-remote`) does not have multiple qualities (this is why the button is hidden). The new demo is miltiquatily and the button is visible.

There was a bug in quality selector. It is fixed now!

**Comment by oas777** [comment]
Fixed.
