### ISSUE TITLE
Colour of the video canvas/background

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#33]
Wouldn't it be good to make the video canvas/background white instead of grey? Look at the difference between 

![grafik](https://user-images.githubusercontent.com/1752342/232069347-4bd857c6-bc74-41fa-8ccc-64d06313327a.png)
and
![grafik](https://user-images.githubusercontent.com/1752342/232069575-73f5b711-8f56-43b6-98b3-36df5cb6e499.png)

I know there's also the control bar disappearing in the first example and some resolution issues to address, but you get the idea.

**Comment by miesgre** [comment]
For me it is a bit strange since the bar would appear floating around. Maybe a border could be added to the video?

| | Gray | White | With border |
| - | ------------- | ------------- | ------------- |
| with bar | ![Captura de pantalla 2023-04-18 a las 11 52 23](https://user-images.githubusercontent.com/2735202/232742071-60487c66-b976-45e9-a8b6-d7d4ab9d9599.png)  | ![Captura de pantalla 2023-04-18 a las 11 52 56](https://user-images.githubusercontent.com/2735202/232742249-23898b1d-ab92-4802-ae24-26a6c7c2a458.png)  | ![Captura de pantalla 2023-04-18 a las 12 05 13](https://user-images.githubusercontent.com/2735202/232744887-1de57de7-fbf5-45a3-afaf-45939501ede8.png) |
| w/o bar | ![Captura de pantalla 2023-04-18 a las 11 54 57](https://user-images.githubusercontent.com/2735202/232742373-ffc1ee1a-d8a6-4749-b12f-3f2cd99a00f2.png) | ![Captura de pantalla 2023-04-18 a las 11 54 08](https://user-images.githubusercontent.com/2735202/232742500-74e47157-0e59-41f8-b9f7-e03aff57b1e7.png)  | ![Captura de pantalla 2023-04-18 a las 12 05 45](https://user-images.githubusercontent.com/2735202/232744949-99468a70-5093-4c54-9317-ba38551827ee.png) |


@oas777, Which one do you prefer?

**Comment by oas777** [comment]
I agree "Gray" looks best with the control bar visible, but that's the case for only a couple of seconds (at least that's the setting here at ETH). Overall, I prefer "White", especially because of the immersion with the white background of most websites when the player is embedded. Maybe Carlos wants to chime in?

**Comment by miesgre** [comment]
@turro?

**Comment by turro** [comment]
Personally I would like to see that white with border, but maybe in the context of the Tobira portal  no-border looks even cleaner.  I would try as Olaf's proposal

**Comment by miesgre** [comment]
I updated the player with white canvas.
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
Great, thanks!

**Comment by oas777** [comment]
Is the background grey again or is this my local cache? Cf. https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls.

**Comment by oas777** [comment]
The background is still grey-ish at https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls. While I'm still in favor of a white background, we're leaning towards "black" in Tobira, mainly for portrait videos. Is this something that is or could be made configurable between those (three) options?

**Comment by miesgre** [comment]
Please check https://polimediaupv.github.io/paella-skins/.
If skin is correct I will update `ethz` repository.

**Comment by oas777** [comment]
+1

**Comment by oas777** [comment]
That's white, yes. Is it configurable?
