### ISSUE TITLE
"Settings" and "Video layout" menu: Coherence

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#46]
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/83d26376-161a-483f-b721-315fe25fc106)
and
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/b8dd276e-cb87-4b43-9104-9dff91a0ffba)

- header with the same font
- header bold, text regular
- header and text centered

Also, the highlighting of the selected option should be coherent (black background vs. glowing text)

**Comment by miesgre** [comment]
Please check https://polimediaupv.github.io/paella-skins/.
If skin is correct I will update `ethz` repository.

**Comment by oas777** [comment]
Yes, thanks! I think there's still some details to be harmonised, but that's for the designer to review and sugest.

**Comment by oas777** [comment]
Can I close this one, too?

**Comment by oas777** [comment]
No, I cannot: The menu for "Captions" has to be adjusted also:
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/91e09525-fa34-49ae-b6d3-722dfb5ba2be)

**Comment by miesgre** [comment]
It's a configuration option. Added in https://polimediaupv.github.io/paella-skins/.

**Comment by oas777** [comment]
You mean one can select whether to have a header or not? For each menu? Because right now it's very different across the three:

![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/84bb8146-1840-441f-8e09-71afb90786d5)
No header, black selection background
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/94f3cee4-9b2a-4897-9e0e-f33780287fe5)
With header, black and blue selection background
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/513ee117-0a13-44c4-8a63-4dca553fbcc9)
With header, black and blue selection background

**Comment by miesgre** [comment]
Yes, each menu is a plugin and you can enable or disable the title in the config.json. For example the Video layout selector:

```json
        "es.upv.paella.layoutSelector": {
            "description": "Video layout",
            "menuTitle": "Video layout",
            "closeParentPopUp": true,
            "showIcons": false
        },
```

- description is the tooltip label
- menuTitle (if defined it will be used as title)
- showIcons: if videoLayout icons are used, if false text is used

The videoLayout and the captions selector have the same behavior. Show a menu with several options where only one can be selected. Title is enabled in both menus.

Blue -> shows the chosen option
black background -> shows the option that has the mouse over it

The Settings Menu is different. It does not show a menu with several options where only one can be selected, That's why there is no blue selected.
The settings menu shows other plugins. When you click on any of them, another window/menu opens.

**Comment by oas777** [comment]
Migrating this to Tobira
